server:
  port: 8001

spring:
  application:
    name: sns-service


  datasource:
    url: jdbc:mysql//${SNS_DATABASE_HOST}:3306/${SNS_DATABASE_NAME}
    username: ${SNS_DATABASE_USER}
    password: ${SNS_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SNS_DATA_REDIS_HOST}
      port: ${SNS_DATA_REDIS_PORT}
      password: ${SNS_DATA_REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.MySQL8Dialect


cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS}



logging:
  level:
    org.springframework: INFO

